"""initial baseline schema (HLD 9)

Creates every table from the ORM metadata so the baseline never drifts from
``app.db.models``. Subsequent revisions are autogenerated
(``alembic revision --autogenerate``). SQL-Server-specific tuning (partitioning,
columnstore) is layered in a later, dialect-guarded revision.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-24
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.db.models import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
